spring.application.name=user_managment_system

spring.mongodb.uri=mongodb+srv://prasannadilshan2002_db_user:llmrGCIu69e3duI7@cluster1.y2qea0r.mongodb.net/user_management?retryWrites=true&w=majority&appName=Cluster1

jwt.secret=5f4dcc3b5aa765d61d8327deb882cf995f4dcc3b5aa765d61d8327deb882cf99
jwt.expiration=86400000
